### PR TITLE
Fix location always bugs

### PR DESCRIPTION
**Pull request by yerkejs**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Bug fix

### :arrow_heading_down: What is the current behavior?
When user installs application for the first time ever and for request "`locationWhenInUse`" selects "Allow once", next "locationAlways" request hangs out without any response. For the second time, if user accepts "Allow while use", next request "locationAlways" is denied. 

### :new: What is the new behavior (if this is a feature change)?
Fixes those bugs

### :boom: Does this PR introduce a breaking change?
Nope

### :memo: Links to relevant issues/docs
https://github.com/Baseflow/flutter-permission-handler/issues/1011
https://github.com/Baseflow/flutter-permission-handler/issues/802
https://github.com/Baseflow/flutter-permission-handler/issues/1018

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md)).
- [X] I updated the relevant documentation.
- [X] I rebased onto current `master`.

### CODE REVIEW

**Comment by typexy** [comment]
wont be merged?

**Comment by yerkejs** [comment]
@typexy no idea, in all PRs CI is failing

**Comment by yerkejs** [comment]
@mvanbeusekom can you suggest someone who could review ?

**Comment by yerkejs** [comment]
@JeroenWeener, @mvanbeusekom let's review and merge please

**Comment by mvanbeusekom** [comment]
Finally got around and debugging this problem my self and I am able to reproduce the but. Although I really appreciate the effort this implementation is not correct and will result into new problems. 

The current implementation will save the permissions to the user defaults (basically to disk) so the status is know between application restarts. The implementation in this PR will remove this logic causing bugs when location always permission is provided and the application restarts. 

The real issue is in the handling of the result when requesting "location always" permission when "only once" has been granted. More specifically on [line 114](https://github.com/Baseflow/flutter-permission-handler/blob/30f497c8f44204e10a79ac4abbbf85ca45808342/permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m#L114). The statement on this line is `true` in the above case, returning the method with out completing and sending back a result to Dart. This causes the Dart side to wait forever.

In this case I feel the correct solution would be to return `PermissionStatus.denied` and complete the future. I will create a new PR with the appropriate bug fix.

**Comment by mvanbeusekom** [comment]
New PR is up: #1082

**Pull request closed without merging**
