### PR TITLE
fix/1158: Return permanentlyDenied for Permission.notification.status

### LINKED ISSUE #1158: [Bug]: Permission.notification.status on Android 33 never returns 'permamentlyDenied', even if request() does
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Windows

### Steps to reproduce

You need an API level 33+ Android device as this is the version that introduced the new runtime https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS permission.

1. Create a new simple application and replace its contents with the code sample below, using this package.
2. Click the 'Request notification permission' button and deny the permission, this results in `denied`, as expected.
3. Click the 'Request notification permission' button again and deny the permission again, this results in `permamentlyDenied`, as expected.
4. From now on, clicking the 'Request notification permission' doesn't show the dialog (Android does this) and returns `permamentlyDenied`, as expected.
5. Click the 'Check notification permission' button, this results in `denied`, which is unexpected.

### Expected results

`Permission.notification.status` correctly resolves to `permamentlyDenied` after the second danial.

### Actual results

`Permission.notification.status` naver resolves to `permanentlyDenied`.

I believe the reason is this line: https://github.com/Baseflow/flutter-permission-handler/blob/permission_handler_android_v11.0.1/permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java#L593. Notification permission has special handling, and checking its status never calls `PermissionUtils.determineDeniedVariant`, like requesting them does. I changed this line to
```java
return PermissionUtils.determineDeniedVariant(activity, Manifest.permission.POST_NOTIFICATIONS);
```
and now I get `permanentlyDenied`.

I will prepare a PR attempting to fix this issue.

### Code sample

<details><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.pink,
      ),
      home: Scaffold(
        body: Builder(
          builder: (context) {
            return Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                    onPressed: () async {
                      final status = await Permission.notification.request();
                      _showSnackBar(context, 'request() resulted in: $status');
                    },
                    child: const Text('Request notification permission'),
                  ),
                  ElevatedButton(
                    onPressed: () async {
                      final status = await Permission.notification.status;
                      _showSnackBar(context, 'status resulted in: $status');
                    },
                    child: const Text('Check notification permission'),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}

void _showSnackBar(BuildContext context, String message) {
  ScaffoldMessenger.of(context)
    ..clearSnackBars()
    ..showSnackBar(
      SnackBar(
        content: Text(message),
      ),
    );
}
```

</details>

### Version

11.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.13.3, on macOS 13.5.2 22G91 darwin-arm64, locale en-DE)
    • Flutter version 3.13.3 on channel stable at /Users/rswierzy/fvm/versions/3.13.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/rswierzy/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • SM S908B (mobile) • R3CTB08NJTT • android-arm64  • Android 13 (API 33)
    • macOS (desktop)   • macos       • darwin-arm64   • macOS 13.5.2 22G91 darwin-arm64
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 117.0.5938.88

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by wujek-srujek**
Fixes #1158.

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [x] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by JeroenWeener** [comment]
Thank you for both raising the issue and creating a fix! Welcome to the community 😄

The PR is almost perfect. The only thing that's remaining is updating the version in `pubspec.yaml`.

**Review by JeroenWeener — CHANGES_REQUESTED** [review]
Almost there! Once you update the version in `pubspec.yaml` we will merge and release.

**Comment by wujek-srujek** [comment]
> Almost there! Once you update the version in `pubspec.yaml` we will merge and release.

Oh shoot, I forgot about this again. Be right up.

**Review by JeroenWeener — APPROVED** [review]
Thanks! Hope to hear from you again 👍

**Pull request merged**
