### PR TITLE
fixbug of not exist getter & update sdk version

### PR DESCRIPTION
**Pull request by fzyzcjy**
### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by mvanbeusekom** [comment]
Duplicate of #453

**Comment by fzyzcjy** [comment]
@mvanbeusekom Hi it seems that the sdk version needs to be changed: `sdk: ">=2.12.0 <3.0.0"`, otherwise the package is not considered as null safe?

**Comment by mvanbeusekom** [comment]
Nope this is not necessary, the current version is the BETA version that was first considered stable null-safe you can see here that both versions are marked with the "Null safety" label:

- https://pub.dev/packages/permission_handler_platform_interface
- https://pub.dev/packages/permission_handler

**Comment by fzyzcjy** [comment]
@mvanbeusekom Aha thanks!

**Pull request closed without merging**
