### PR TITLE
Fix/1174 background refresh status

### LINKED ISSUE #1174: [Feature request]: iOS backgroundRefreshStatus
### Is there already an issue requesting this feature?

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).

### Please select affected platform(s)

- [ ] Android
- [X] iOS
- [ ] Windows

### Use case

On iOS users can disable Background App Refresh permission `backgroundRefreshStatus`, due to which background tasks cannot run if user has disabled the permission.
Background tasks are all types of tasks like `Background Fetch`, `BGAppRefreshTask`, `BGProcessingTask`, if the permission is disabled Apps cannot run tasks like daily maintenance, backups, background data processing, or periodic refreshes from server etc

Background App Refresh permission:
image

### Proposal

A new permission handler should be created to get `backgroundRefreshStatus` so that Apps would be able to check and prompt the user to enabled Background App Refresh in App settings

### Specific requirements or considerations

_No response_

### Additional information or context

_No response_

### PR DESCRIPTION
**Pull request by ened**
*Replace this paragraph with a short description of what issue this pull request (PR) solves and provide a description of the change.  Consider including before/after screenshots.*

*List at least one fixed issue.*

## Pre-launch Checklist

- [x] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [x] I added new tests to check the change I am making, or this PR does not need tests.
- [x] I made sure all existing and new tests are passing.
- [x] I ran `dart format .` and committed any changes.
- [x] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

closes #1174

### CODE REVIEW

**Comment by ened** [comment]
@mvanbeusekom the version handling for all the packages seems a little difficult at the moment.. did we discuss introducing [melos](https://melos.invertase.dev) before to handle this better?

**Comment by mvanbeusekom** [comment]
> @mvanbeusekom the version handling for all the packages seems a little difficult at the moment.. did we discuss introducing [melos](https://melos.invertase.dev) before to handle this better?

Hi @ened,

Thank you for this contribution. It looks really nice with a few small remarks. Regarding your question, we try to follow a similar workflow as the Google team does in their [packages](https://github.com/flutter/packages) repo. Meaning we like to split up additions over multiple pull requests. One PR for the platform interface changes, once that is published a PR for each of the platform specific implementations and lastly when those are published a PR for the app-facing package. 

We have worked with Melos before but feel that for our plugins, Melos will make things harder to maintain (since we need to maintain additional configuration) plus it would require other developers/ contributors to also install a separate package. Especially developers who are not familiar with Melos and do not know what is happening under the hood, might get confused or make mistakes when creating their PRs.

However I am curious what it is that you are running into and willing to see if there are ways (maybe through better documentation) to take away these complexities?

**Comment by mvanbeusekom** [comment]
Main feedback for this PR would be to also add (reserve) the `BackgroundRefresh` integer (`36`) in Android native and Windows native code. We have had cases in the past where permissions got mixed up and reserving the integer before hand is the best solution to prevent these situations.

P.S. we are currently actively refactoring the code base making the need to reserving integers no longer needed, however until that time please do.

**Review by mvanbeusekom — APPROVED** [review]
Thanks @ened for all this work, look good to me. I will just merge it into a separate branch and create three new PRs so I can make individual releases:

1. One PR with the changes to the platform interface.
2. A second PR with the changes to the platform specific packages.
3. A third PR with the changes to the permission_handler app facing package.

I'll add you as author. Just wanted to inform you, so you know what is happening.

**Pull request merged**
