### PR TITLE
migrate to package:web

### LINKED ISSUE #1302: [Enhancement proposal]: Add wasm support
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-permission-handler/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-permission-handler/blob/main/permission_handler/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Windows
- [x] Web

### Proposal

web plugin is using `dart:html` which is not compatible with WASM, migrate to [package:web](https://pub.dev/packages/web).

Context: The unavailable library 'dart:html' is imported through these packages:
    web_plugin_registrant.dart => package:permission_handler_html => dart:html

### Pitch

Flutter doc: https://docs.flutter.dev/platform-integration/web/wasm

### PR DESCRIPTION
**Pull request by raldhafiri**
Migrated to package:web, meaning that it now supports WASM!

Fix #1302

### CODE REVIEW

**Comment by james-pellow** [comment]
I'd just like to add my support for this.  In my reasonably complex application, this is the only package preventing us from compiling to wasm.  I have reviewed this patch and it looks correct to me.  Is there something that is holding this up?  Thanks!

**Comment by raldhafiri** [comment]
> I'd just like to add my support for this. In my reasonably complex application, this is the only package preventing us from compiling to wasm. I have reviewed this patch and it looks correct to me. Is there something that is holding this up? Thanks!

I would recommend you to create `pubspec_overrides.yaml` and use it until it get merged or fork my repo 
I know its not the best solution but hopefully it will be merged soon to support WASM

```
dependency_overrides:
  permission_handler_html:
    git:
      url: https://github.com/raldhafiri/flutter-permission-handler.git
      ref: main
      path: permission_handler_html
```

**Comment by koji-1009** [comment]
Thanks for the great PR. Can't wait to see it merged.

How about updating `index.html` to the template added in flutter 3.22.0? So we can test the build for wasm and it will be easier to make sure it works.

**Comment by Padi142** [comment]
Bump

**Comment by hasanm08** [comment]
can you merge it faster and deploy on pub.dev?
@james-pellow 
@koji-1009 
@Padi142 
@bramp

**Comment by koji-1009** [comment]
@raldhafiri 
I have created a commit to update the example project with the flutter 3.22 template. Could you please check the commit? If necessary, I will create a PR for the branch you are developing. Thanks.

https://github.com/koji-1009/flutter-permission-handler/commit/b2f97273fb2bf2f91725b75ef2a168f5bd1a1739

**Comment by MominRaza** [comment]
@mvanbeusekom @gmackall Please review this

**Comment by Brada-Groep** [comment]
Can someone merge this please? :)

**Review by mvanbeusekom — APPROVED** [review]

**Comment by mvanbeusekom** [comment]
On popular demand, this PR has just been merged and published. 

Run `flutter pub upgrade permission_handler_html` to download the latest version in your project.

**Pull request merged**
