### PR TITLE
Adding SiriKit permissions

### PR DESCRIPTION
**Pull request by dupuchba**
Hello folks,

Here is the code to add SiriKit to the project.
It lacks example and some todo in the checklist but if someone can at least tell me if the code complies to the project standards it would be awesome.

I would complete other checklist in the next 48 hours

## Pre-launch Checklist

- [X] I made sure the project builds.
- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [ ] I made sure all existing and new tests are passing.
- [X] I ran `dart format .` and committed any changes.
- [ ] I ran `flutter analyze` and fixed any errors.

[Contributor Guide]: https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by mvanbeusekom** [comment]
Hi @dupuchba,

Thank you for taking the time and contributing to the plugin. 

I have gone through the PR and the changes look good and we would be happy to adopt them in the code base. I do however have one request, since this required adding a new entry to the `Permissions` enum we'd like this also to be reserved/ added to the enum in all implementation packages (in the native code base). 

In the past we had problems where permissions were mistakenly mixed and we are trying to prevent this from happening again by making sure permissions are reserved in all platforms (even if those permissions are no-op on those platforms).

**Comment by dupuchba** [comment]
@mvanbeusekom thanks for the review, which file are you talking about? I've added it to `PermissionHandlerEnums`

**Comment by mvanbeusekom** [comment]
> @mvanbeusekom thanks for the review, which file are you talking about? I've added it to `PermissionHandlerEnums`

Hi @dupuchba,

All platform specific implementation packages (with the exception of `permission_handler_html`) contain a file defining the permission enum in there respective native programming language. The new enum value should also be added there to "reserve" the integer value. These files are:

- [PermissionConstants.java](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java) on Android.
- [permission_constants.h](https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_windows/windows/permission_constants.h) on Windows

**Comment by dupuchba** [comment]
@mvanbeusekom sorry and thank you. I was not able to find time these last few weeks... I have a big open source project myself and it can be time consuming...
Thanks a lot for your work / support!

**Pull request merged**
