### PR TITLE
Added support for the 3 new Bluetooth permissions of Android 12.

### PR DESCRIPTION
**Pull request by PieterAelse**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
1. Added support for the 3 new Bluetooth permissions of Android 12:
- BLUETOOTH_SCAN
- BLUETOOTH_ADVERTISE
- BLUETOOTH_CONNECT
2. Updated Android compile and target SDK to 31 (Android 12 (S)).
3. Updated Gradle and dependencies of Android project.
4. Updated applicationID of example app

See #560 and documentation here: https://developer.android.com/about/versions/12/features/bluetooth-permissions 

### :arrow_heading_down: What is the current behavior?
No support.

### :new: What is the new behavior (if this is a feature change)?
Yes support.

### :boom: Does this PR introduce a breaking change?
No.

### :bug: Recommendations for testing
Test on Android 12 device.

### :memo: Links to relevant issues/docs
- See issue #560 
- The pubspec.yaml file of `permission_hanlder` needs to be updated to use the new version of `permission_handler_platform_interface` once that's pushed (I don't have the rights of course). I'm using `path` now to make it work locally.

### :thinking: Checklist before submitting

- [X] I made sure all projects build.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I followed the style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/master/CONTRIBUTING.md)).
- [X] I updated the relevant documentation.
- [X] I rebased onto current `master`.

### CODE REVIEW

**Comment by mvanbeusekom** [comment]
Hi @PieterAelse, 

Thanks a lot for this PR, it looks really good. I have just two questions:

1. Would you please also "reserve" the permission enums in the iOS version of the plugin? This is to prevent mistakes when adding new permissions to iOS. You could simply add them to the `PermissionGroup` typedef in the [PermissionEnumHandler.h](https://github.com/Baseflow/flutter-permission-handler/blob/8d0d47bde67c12aa12c492f3e66cbc3626be22af/permission_handler/ios/Classes/PermissionHandlerEnums.h) file;
2. By changing the `compileSdkVersion` in the android/build.gradle` file to `31` we are forcing all users to do the same. I am not sure if it is already ok to this or to hold off until Android 12 is released as stable. How do you feel about this?

**Comment by PieterAelse** [comment]
@mvanbeusekom You're welcome! Happy to contribute as we're also using the plugin :D 

1. Ah good catch, did that and pushed an update!
2. I don't think **compiling** on SDK 31 (`compileSdkVersion) is an issue, as the plugin is not setting the `targetSdkVersion` or `minSdkVersion` it up to the users app to use the version they want. I've tried this branch on an Android 11 device and did not run into an issue.

The only risk is when somebody uses the library on an Android 11 (or lower) device and wants to use the newer permissions, but that is covered/blocked by the checks on version here: https://github.com/PieterAelse/flutter-permission-handler/blob/issue/560/android_12_new_bluetooth_permissions/permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java#L259-L272

**Comment by mvanbeusekom** [comment]
@PieterAelse thank you for the update. 

I noticed that the unit tests are failing because of a change in Flutter 2.5. I have applied some fixes this morning and merged them in `master` (see PR #674). Would you mind rebasing your PR with master and hopefully the tree will turn green afterwards.

**Comment by PieterAelse** [comment]
@mvanbeusekom The task "permission_handler_platform_interface / Analyze (pull_request)" will not turn green, because I'm using a `path` reference in the `pubspec.yaml` in order to build/use the branch, see: https://github.com/PieterAelse/flutter-permission-handler/blob/issue/560/android_12_new_bluetooth_permissions/permission_handler/pubspec.yaml#L20 

I will rebase (and fix conflicts) later today, or maybe tomorrow, have a busy day today :D

**Comment by mvanbeusekom** [comment]
> @mvanbeusekom The task "permission_handler_platform_interface / Analyze (pull_request)" will not turn green, because I'm using a `path` reference in the `pubspec.yaml` in order to build/use the branch, see: https://github.com/PieterAelse/flutter-permission-handler/blob/issue/560/android_12_new_bluetooth_permissions/permission_handler/pubspec.yaml#L20
> 
> I will rebase (and fix conflicts) later today, or maybe tomorrow, have a busy day today 😄

Ok yes no problem, I will fix that later (normally we would make separate pull request, one for the platform interface and when that is published one for the implementation, which avoids this problem). However I am willing to fix it afterwards. In this case I am most interested in the unit tests to go green so we are sure nothing breaks.

**Review by mvanbeusekom — APPROVED** [review]
LGTM

**Pull request merged**
