### PR TITLE
Relands bug fix for permission check in background

### PR DESCRIPTION
**Pull request by ened**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bugfix

### :arrow_heading_down: What is the current behavior?

Can not check permission in BG service.

See https://github.com/Baseflow/flutter-permission-handler/pull/252 for a similar fix.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by ened** [comment]
This project could do with a extensive e2e test suite.

**Comment by mvanbeusekom** [comment]
HI @ened, thanks again for supplying this bug fix. If I am not mistaken the real solution here is adding the `@Nullable` attribute to the `activity` parameter of the `determinePermissionStatus` method. I am wondering why did it go wrong in the first place, how come it was removed? As far as I can see it has never been there and on issue #233 you have confirmed the code was working correctly. 

I am trying to think how I can test changes better to prevent these kind of mistakes in the future. As you mentioned the project indeed could use a good e2e test suite and I have been playing around with it but unfortunately without a lot of success (I keep on running into error when running the `flutter drive` command). One thing that would be very helpful is we could somehow add some background functionality to the example app so we can at least run that and see if it fails. Would this be something you think is an option and maybe even something you are willing to help out with?

Besides this, the code in the PR looks good and I will merge and release it later this week.

**Comment by ened** [comment]
The `@Nullable` annotation can be omitted, it's just there fore clarity.

The support library method to determine the "neverAskAgain" status internally checks if activity is null and if so just returns false, which means in the permission_handler code, the next else branch is called up.

Main change is the removal of the `activity` requirement to check for the status and this was solved in the same way in #233. I believe that issue was handling V4 of the permission_handler plugin.

Rgd. the E2E tests, something can be done, given the recent improvements in the `e2e` plugin. It is now possible run service/activity tests with permissions pre-granted, which is nice. The only issue is how to get the information on which native tests is being run at the moment up to the Dart e2e code. I'll try to update the simple e2e tests for this plugin in a separate PR.

**Comment by mvanbeusekom** [comment]
I see now where you removed the `if(activity == null)` block, this indeed came back when we refactored the plugin into 5.0. The changes in issue #233 happened at the same time and I guess this wasn't merged in correctly when sifting through the merge conflicts.

**Comment by mvanbeusekom** [comment]
And of course looking forward to your PR regarding the e2e tests. Even a simple setup might be helpful to get me started and to expand upon.

**Pull request merged**
