### PR TITLE
Workaround for ignore battery optimizations on pre-M

### PR DESCRIPTION
**Pull request by ened**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

The ignore battery optimisation setting is not available on Android devices < M; and surprisingly those devices will then also have the item removed from their AndroidManifest.xml reader at runtime (?). 

In such case, the permission should be returned as "restricted"; a better name would be "unavailable".

I'm marking this as WIP for the moment, until testing has completed here.

### :arrow_heading_down: What is the current behavior?

Permission is continuously returned as undetermined on such devices.

### :new: What is the new behavior (if this is a feature change)?

Permission is returned as "restricted".

### :boom: Does this PR introduce a breaking change?

No.

### :bug: Recommendations for testing

Install the example app on a variety of Android phones, ranging from 4.4 to 8.0 at least.

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter-permission-handler/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Comment by ened** [comment]
We have been running on this fork for a few months now, therefore removing WIP label &requesting a review.  @mvanbeusekom

**Comment by mvanbeusekom** [comment]
@ened we are on the verge of releasing a new major version of the permission_handler which is removing the `PermissionStatus.notDetermined` and fallback to the default Android behaviour where we assume permissions are denied until explicitly told otherwise by the end user. Storing permissions in shared preferences is turning out to be a problem since the introduction of permission changes on Android API 30. 

This will also impact this PR since the `PermissionConstants.PERMISSION_STATUS_NOT_DETERMINED` will be removed all together. Would you mind updating this code once the other PR (#453) is merged?

**Comment by ened** [comment]
> This will also impact this PR since the `PermissionConstants.PERMISSION_STATUS_NOT_DETERMINED` will be removed all together. Would you mind updating this code once the other PR (#453) is merged?

OK no problem, I will wait for #453.

**Comment by ened** [comment]
@mvanbeusekom rebased

**Review by mvanbeusekom — APPROVED** [review]
LGTM, thanks again @ened

**Pull request merged**
